USE [master]
GO

/****** Object:  Database [ComicBookStoreASP]    Script Date: 8.6.2023. 19:25:20 ******/
CREATE DATABASE [ComicBookStoreASP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ComicBookStoreASP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ComicBookStoreASP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ComicBookStoreASP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ComicBookStoreASP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ComicBookStoreASP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ComicBookStoreASP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET ARITHABORT OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ComicBookStoreASP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ComicBookStoreASP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ComicBookStoreASP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ComicBookStoreASP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ComicBookStoreASP] SET  MULTI_USER 
GO

ALTER DATABASE [ComicBookStoreASP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ComicBookStoreASP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ComicBookStoreASP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ComicBookStoreASP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ComicBookStoreASP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ComicBookStoreASP] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ComicBookStoreASP] SET  READ_WRITE 
GO


